name: Fuzz Test
on: [push, pull_request]

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Generate
        run: go generate -v ./...

      - name: Build
        run: go build cmd/board.go

      - name: Run
        run: ./board &

      - uses: schemathesis/action@v2
        with:
          schema: './api/openapi.yaml'
          args: >-
            --url "http://localhost:8080"
